---
title: "Analyses Preliminaires version 1.1"
author: "Nicolas Migueres"
date: "29 janvier 2020"
output:
  word_document: default
  toc: yes
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE,message=TRUE,warning=TRUE}
knitr::opts_chunk$set(echo = FALSE)
```

# Analyse de la cohorte EUPHOCAS, projet T2/non T2

```{r nettoyage des données,include=FALSE,message=FALSE,warning=FALSE,echo=FALSE}
library(readxl)
DATA<- read_excel(path="EAACI - Occupational Asthma - all DATAbases 2006-2018 - 1518-Nicolas.xlsx",sheet=1,na=c("NA", "N A", "N / A", "N/A", "N/ A", "Not Available", "NOt available","","not available","not avaiable","no available", "not avaliable","nd","not performed","not avalaible","not applicable (not removed)","not applicable","Not applicable","Not available"),col_names = TRUE)

DATAREF<-DATA

library("kableExtra")
library("tableone")
library('stringr')
library("devtools")
library("Amelia")
library("questionr")
library("ggplot2")
library("wesanderson")
library("lmtest")
library("tidyr")
library("naniar")

#nettoyage de la base de donnee

colnames(DATA)[colnames(DATA)=="CODE_CENTER_COUNTRY"] <- "COUNTRY"
colnames(DATA)[colnames(DATA)=='CODE_CENTER_CITY']<-"CITY"
colnames(DATA)[colnames(DATA)=="DIAGNOSIS_SIC"]<-"DIAGNOSIS"
DATA$DIAGNOSIS<-as.factor(DATA$DIAGNOSIS)
colnames(DATA)[colnames(DATA)=="HEIGHT (in cm)"]<-"HEIGHT"
DATA$HEIGHT<-DATA$HEIGHT/100
DATA$BMI.CAT<-as.factor(DATA$BMI.CAT)
DATA$SEX<-as.factor(DATA$SEX)
DATA$SEX[DATA$SEX%in%c("F")]<-"female"
DATA$SEX[DATA$SEX%in%c("M")]<-"male"
DATA$RACE<-tolower(DATA$RACE)
DATA$RACE<-factor(DATA$RACE)
DATA$EDUCATION<-tolower(DATA$EDUCATION)
DATA$EDUCATION<-factor(DATA$EDUCATION)
DATA$JOB<-tolower(DATA$JOB)
DATA$JOB<-factor(DATA$JOB)
DATA$JOB[DATA$JOB%in%c("mechanical engineers")]<-"mechanical engineer"
DATA$JOB[DATA$JOB%in%c("cooker")]<-"cook"
DATA$JOB[DATA$JOB%in%c("cabinet-maker")]<-"cabinetmaker"
DATA$JOB[DATA$JOB%in%c("care assisstant")]<-"care assistant"
DATA$JOB[DATA$JOB%in%c("saw mill worker","saw mill operative")]<-"sawmill worker"
DATA$JOB[DATA$JOB%in%c("hair dresser")]<-"hairdresser"
DATA$JOB_CLASS<-tolower(DATA$JOB_CLASS)
DATA$JOB_CLASS<-factor(DATA$JOB_CLASS)
DATA$AGENT_NAME<-tolower(DATA$AGENT_NAME)
DATA$AGENT_NAME<-as.character(DATA$AGENT_NAME)
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("isocyanates")]<-"isocyanate"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("flours")]<-"flour"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("acideanhydride","acide anhydride","acidanhydrides","anhydre","anhydrides")]<-"acid anhydride"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("persulfates","persuphates","persulphate salts","persulphates","persulfate salts")]<-"persulfate"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("acrylates","acrilic polymer")]<-"acrylate"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("ammonium persulfates","ammonium persulphate","ammoniumapersulphate","ammoniumpersulphate")]<-"ammonium persulfate"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("cow epithel","cow hair","cow epithelia","bovine hair")]<-"cow epithelium"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("paint  and solvents","paints and solvants")]<-"paints and solvents"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("drugs")]<-"drug"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("epoxide","epoxi")]<-"epoxy"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("thiamne")]<-"thiamine" 
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("gypsophila plant")]<-"gypsophila" 
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("cyanoacrylates")]<-"cyanoacrylate"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("wheat + rye flour" )]<-"wheat and rye flour"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("chromium")]<-"chronium"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("animal hairs")]<-"animal hair"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("mdi-icocyanate")]<-"mdi-isocyanate"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("methacrylates")]<-"methacrylate"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("mhhpa acid anhydride","mhhpanhydride")]<-"mhhpa anhydride"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("mouse","mouse epithelia")]<-"mouse epithelium"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("obechewood dust")]<-"obeche wood dust"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("horse","horse epithelial")]<-"horse epithelium"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("platinum salts")]<-"platinum salt"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("epoxy resine")]<-"epoxy resin"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("didecyl-diammonium","didecyl-dymethyl chloramonium","didecyl dimethyl ammonium chloride")]<-"didecyl-dimethyl ammonium chloride"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("isocyanate(hdi)","hdi-isoyanate","hdi-isocyanate","hdi hexamethylene-1,6 di isocyanate")]<-"isocyanate hdi"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("cyanoacrilate","cianoacrylates")]<-"cyanoacrylate"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("isocyanate- mdi")]<-"isocyanate mdi"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("quat ammonium")]<-"quaternary ammonium"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("stainless steel ")]<-"stainless steel"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("red cedar")]<-"red cedar wood"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("rat epitelium")]<-"rat epithelium"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("wood dusts","wood")]<-"wood dust"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("wheat")]<-"wheat flour"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("storage dust mite lepidoglyphus destructor")]<-"storage mite lepidoglyphus destructor"
DATA$AGENT_NAME[DATA$AGENT_NAME%in%c("aldehydes","aldehydes;benzenic solvants","aldéhydes","aldehydes; benzenic solvants")]<-"aldehyde"
DATA$AGENT_NAME<-factor(DATA$AGENT_NAME)
colnames(DATA)[colnames(DATA)=="AGENT_NEW_CATEGORY"]<-"AGENT_CATEGORY"
DATA$AGENT_CATEGORY[DATA$AGENT_CATEGORY%in%c("Enzymes","enzyme")]<-"enzymes"
DATA$AGENT_CATEGORY<-as.factor(DATA$AGENT_CATEGORY)
DATA$AGENT_CATEGORY<-tolower(DATA$AGENT_CATEGORY)
colnames(DATA)[colnames(DATA)=="AGENT_MOLECULAR WEIGHT"]<-"HMW.LMW"
DATA$HMW.LMW<-as.character(DATA$HMW.LMW)
DATA$HMW.LMW[DATA$HMW.LMW%in%c("unknown")]<-NA
DATA$HMW.LMW<-factor(DATA$HMW.LMW)
DATA$SMOKER<-tolower(DATA$SMOKER)
DATA$SMOKER<-factor(DATA$SMOKER)
DATA$ASTHMA_PRE<-as.factor(DATA$ASTHMA_PRE)
colnames(DATA)[colnames(DATA)=="AGE_ASTHMA_ONSET (<12 years, 12-18 years or age)"]<-"AGE_ONSET_CAT"
DATA$AGE_ONSET_CAT<-as.character(DATA$AGE_ONSET_CAT)

#On impute la valuer d'age 11 pour les individu <12 ans sans specification et 15 pour >12<18 afin de transformer secondairement en variable catégorielle en 3 classes.

DATA$AGE_ONSET_CAT<-ifelse(as.character(DATA$AGE_ONSET_CAT)%in%c("<12","<12 ","<12 years","< 12" ),"11",as.character(DATA$AGE_ONSET_CAT))
DATA$AGE_ONSET_CAT<-ifelse(as.character(DATA$AGE_ONSET_CAT)%in%c(" 12-18"," 12-18 ","12-18 years","12-18"),"15",as.character(DATA$AGE_ONSET_CAT))
DATA$AGE_ONSET_CAT<-as.numeric(DATA$AGE_ONSET_CAT)
DATA$AGE_ONSET_CAT<-cut(DATA$AGE_ONSET_CAT,breaks = c(0,12,19,100),include.lowest = TRUE,labels = c("<12","12-18",">18"))

DATA$ATOPY<-as.factor(DATA$ATOPY)

colnames(DATA)[colnames(DATA)=="SENSITIZATION TO ASPERGILLUS"]<-"ASPER"
DATA$ASPER<-tolower(DATA$ASPER)
DATA$ASPER<-as.factor(DATA$ASPER)

colnames(DATA)[colnames(DATA)=="TOTAL_IGE (KU/l)"]<-"IGET"
DATA$IGET<-as.factor(DATA$IGET)
DATA$IGET<-ifelse(as.character(DATA$IGET)%in%c("<2","below detection limit","no"  ),"0",as.character(DATA$IGET))
DATA$IGET<-as.numeric(DATA$IGET)

DATA$SABA_W_FREQUENCY<-as.character(DATA$SABA_W_FREQUENCY)
DATA$SABA_W_FREQUENCY[DATA$SABA_W_FREQUENCY%in%c("≥3 times a day","?3 times a day")]<-"3 times a day or more"
DATA$SABA_W_FREQUENCY<-as.factor(DATA$SABA_W_FREQUENCY)

DATA$SABA_SIC_FREQUENCY<-as.character(DATA$SABA_SIC_FREQUENCY)
DATA$SABA_SIC_FREQUENCY[DATA$SABA_SIC_FREQUENCY%in%c("≥3 times a day","?3 times a day")]<-"3 times a day or more"
DATA$SABA_SIC_FREQUENCY<-as.factor(DATA$SABA_SIC_FREQUENCY)


DATA$ASPER<-as.character(DATA$ASPER)
DATA$ASPER[DATA$ASPER%in%c("0.34","2.41")]<-"yes"
DATA$ASPER<-as.factor(DATA$ASPER)


colnames(DATA)[colnames(DATA)=="DELAY_ASTHMA (month)"]<-"ASTHMA_DELAY"
colnames(DATA)[colnames(DATA)=="D_SX_W (month)"]<-"ASTHMA_WORK_TIME"
DATA$SINUSITIS<-as.factor(DATA$SINUSITIS)

colnames(DATA)[colnames(DATA)=="Gastrooesophageal reflux - PPI Treatment"]<-"GER"
DATA$GER<-as.factor(DATA$GER)
DATA$COUGH_W<-as.factor(DATA$COUGH_W)
DATA$WHEEZING_W<-as.factor(DATA$WHEEZING_W)
DATA$DYSPNEA_W<-as.factor(DATA$DYSPNEA_W)
DATA$TIGHTNESS_W<-as.factor(DATA$TIGHTNESS_W)
DATA$SPUTUM<-as.factor(DATA$SPUTUM)
DATA$RHINITIS_W<-as.factor(DATA$RHINITIS_W)

DATA$ONSET_OF_RHINITIS_W[DATA$ONSET_OF_RHINITIS_W%in%c("post")]<-"after"
DATA$ONSET_OF_RHINITIS_W<-as.factor(DATA$ONSET_OF_RHINITIS_W)

DATA$CONJONCT_W<-as.factor(DATA$CONJONCT_W)
DATA$ECZEMA_W<-as.factor(DATA$ECZEMA_W)
DATA$URTICARIA_W<-as.factor(DATA$URTICARIA_W)
DATA$DYSPHONIA_W<-as.factor(DATA$DYSPHONIA_W)
DATA$PRICK_TEST<-as.factor(DATA$PRICK_TEST)
DATA$SPECIFIC_IGE<-as.factor(DATA$SPECIFIC_IGE)
DATA$IgE_MEDIATED_OA<-as.factor(DATA$IgE_MEDIATED_OA)
DATA$DPEF_W<-as.factor(DATA$DPEF_W)
DATA[sapply(DATA, is.character)] <- lapply(DATA[sapply(DATA, is.character)],as.factor)
DATA$DNSBH_W<-as.character(DATA$DNSBH_W)
DATA$DNSBH_W[DATA$DNSBH_W%in%c("positive")]<-"yes"
DATA$DNSBH_W<-as.factor(DATA$DNSBH_W)

colnames(DATA)[colnames(DATA)=="ICS_W_DOSE  (Mcg/day)"]<-"ICS_W_DOSE"
colnames(DATA)[colnames(DATA)=="ICS_W_DOSE GINA"]<-"ICS_W_GINA"
colnames(DATA)[colnames(DATA)=="LAMA_W (yes/no)"]<-"LAMA_W"
colnames(DATA)[colnames(DATA)=="OCS_W (Mg/day)"]<-"OCS_W_DOSE"
colnames(DATA)[colnames(DATA)=="TIME_LAST_EXP (month)"]<-"TIME_LAST_EXP_M"

colnames(DATA)[colnames(DATA)=="TIME_LAST_EXP ≤ 0,1 (3days)"]<-"TIME_LAST_EXP_D"

colnames(DATA)[colnames(DATA)=="ICS_SIC_DOSE (Mcg/day)"]<-"ICS_SIC_DOSE"
colnames(DATA)[colnames(DATA)=="ICS_SIC_DOSE GINA"]<-"ICS_SIC_GINA"


colnames(DATA)[colnames(DATA)=="OCS_SIC (Mg/day)"]<-"OCS_SIC_DOSE"
colnames(DATA)[colnames(DATA)=="FEV1/FVC"]<-"FEV1_FVC"
colnames(DATA)[colnames(DATA)=="BASELINE_FEV1<80%"]<-"BASELINE_FEV1_80"

DATA$NSBH_AGENT<-tolower(DATA$NSBH_AGENT)
DATA$NSBH_METHOD<-tolower(DATA$NSBH_METHOD)
DATA$NSBH_AGENT<-factor(DATA$NSBH_AGENT)
DATA$NSBH_METHOD<-factor(DATA$NSBH_METHOD)

DATA$ASTHMA_DIAGNOSIS[DATA$ASTHMA_DIAGNOSIS%in%c("positive")]<-"yes"
DATA$ASTHMA_DIAGNOSIS[DATA$ASTHMA_DIAGNOSIS%in%c("negative")]<-"no"

DATA$NSBH_RESULT<-as.character(DATA$NSBH_RESULT)
DATA$NSBH_RESULT[DATA$NSBH_RESULT%in%c("positivie")]<-"positive"
DATA$NSBH_RESULT<-as.factor(DATA$NSBH_RESULT)

colnames(DATA)[colnames(DATA)=="Patterns of reaction"]<-"TYPE_REACTION"
DATA$TYPE_REACTION<-as.character(DATA$TYPE_REACTION)
DATA$TYPE_REACTION[DATA$TYPE_REACTION%in%c("early reaction")]<-"isolated early"
DATA$TYPE_REACTION[DATA$TYPE_REACTION%in%c("late reaction")]<-"isolated late"
DATA$TYPE_REACTION<-as.factor(DATA$TYPE_REACTION)


colnames(DATA)[colnames(DATA)=="DUR_EXPO_SIC (minutes)"]<-"DUR_EXPO_SIC"

colnames(DATA)[colnames(DATA)=="CHANGE_NSBH_SIC_BASELINE/24"]<-"NSBH_SIC_RATIO"
colnames(DATA)[colnames(DATA)=="CHANGE_NSBH ≥2"]<-"NSBH_SIC_MAX_RATIO"
colnames(DATA)[colnames(DATA)=="BLOOD_EOSINO≥300/mm³"]<-"BLOOD_EOSINO_300"
colnames(DATA)[colnames(DATA)=="FENO_PRE_SIC<25"]<-"FENO_PRE_SIC.25"
colnames(DATA)[colnames(DATA)=="FENO_PRE_SIC_25_50"]<-"FENO_PRE_SIC.25.50"
colnames(DATA)[colnames(DATA)=="FENO_PRE_SIC_50"]<-"FENO_PRE_SIC.50"



colnames(DATA)<-gsub("_%_",x=colnames(DATA),"_")
colnames(DATA)<-gsub("≥",x=colnames(DATA),"_")
colnames(DATA)<-gsub("%",x=colnames(DATA),"")
colnames(DATA)<-gsub("__",x=colnames(DATA),"_")
colnames(DATA)<-gsub("<",x=colnames(DATA),"_")
colnames(DATA)<-gsub("17,5ppb",x=colnames(DATA),"17.5")


colnames(DATA)[colnames(DATA)==c("FENO_PRE_SIC_25_50")]<-"FENO_PRE_SIC_25.50"
colnames(DATA)[colnames(DATA)==c("FENO_PRE_SIC_50")]<-"FENO_PRE_SIC.50"
colnames(DATA)[colnames(DATA)==c("NEUTRO_PRE_SIC_61")]<-"NEUTRO_PRE_SIC.61"
colnames(DATA)[colnames(DATA)==c("NEUTRO_PRE_SIC_76")]<-"NEUTRO_PRE_SIC.76"
colnames(DATA)[colnames(DATA)==c("NEUTRO_PRE_SIC (x106/ml)")]<-"NEUTRO_PRE_SIC_CELL"
colnames(DATA)[colnames(DATA)==c("NEUTRO_POST_24_SIC")]<-"NEUTRO_POST_SIC"
colnames(DATA)[colnames(DATA)==c("NEUTRO_POST_24_SIC (x106/ml)")]<-"NEUTRO_POST_SIC_CELL"
colnames(DATA)[colnames(DATA)==c("NEUTRO_POST_24_SIC_76")]<-"NEUTRO_POST_SIC.76"
colnames(DATA)[colnames(DATA)==c("Sutum Pattern PRE_SIC")]<-"SPUTUM_PRE_SIC"

colnames(DATA)[colnames(DATA)==c("EOSINO_PRE_SIC_2,2")]<-"EOSINO_PRE_SIC.2.2"
colnames(DATA)[colnames(DATA)==c("EOSINO_PRE_SIC_3")]<-"EOSINO_PRE_SIC.3"
colnames(DATA)[colnames(DATA)==c("EOSINO_PRE_SIC (x106/ml)")]<-"EOSINO_PRE_SIC_CELL"
colnames(DATA)[colnames(DATA)==c("EOSINO_POST_24_SIC")]<-"EOSINO_POST_SIC"
colnames(DATA)[colnames(DATA)==c("EOSINO_POST_24_SIC (x106/ml)")]<-"EOSINO_POST_SIC_CELL"
colnames(DATA)[colnames(DATA)==c("Sputum pattern Post SIC")]<-"SPUTUM_POST_SIC"
colnames(DATA)[colnames(DATA)==c("EOSINO_POST_24_SIC_3")]<-"EOSINO_POST_SIC.3"

colnames(DATA)[colnames(DATA)==c("CHANGE_EOSINO_3")]<-"CHANGE_EOSINO.3"

colnames(DATA)[colnames(DATA)==c("BLOOD_EOSINO_300/mm³ or FENO _ 50ppb or Eosino _ 3")]<-"T2OR50"


DATA$CHANGE_FENO_17.5<-as.character(DATA$CHANGE_FENO_17.5)
DATA$CHANGE_FENO_17.5[DATA$CHANGE_FENO_17.5==c("n")]<-'no'
DATA$CHANGE_FENO_17.5<-factor(DATA$CHANGE_FENO_17.5)

DATA$SPUTUM_PRE_SIC<-as.character(DATA$SPUTUM_PRE_SIC)
DATA$SPUTUM_PRE_SIC[DATA$SPUTUM_PRE_SIC==c("eosiniphilic")]<-'eosinophilic'
DATA$SPUTUM_PRE_SIC<-factor(DATA$SPUTUM_PRE_SIC)

DATA$SPUTUM_POST_SIC<-as.character(DATA$SPUTUM_POST_SIC)
DATA$SPUTUM_POST_SIC[DATA$SPUTUM_POST_SIC==c("paucigranolucytic")]<-'paucigranulocytic'
DATA$SPUTUM_POST_SIC<-factor(DATA$SPUTUM_POST_SIC)



DATA$STATUS_SIC<-tolower(DATA$STATUS_SIC)
DATA$STATUS_SIC<-factor(DATA$STATUS_SIC)
colnames(DATA)<-tolower(colnames(DATA))

DATA$nsbh.res<-as.character(DATA$nsbh.res)
DATA$nsbh.res[DATA$nsbh.res%in%c("severe to moderate")]<-"moderate to severe"
DATA$nsbh.res<-as.factor(DATA$nsbh.res)
DATA$nsbh.res<-factor(DATA$nsbh.res,c("negative","mild","moderate to severe"))

DATA$only_early<-NULL
for(i in 1:dim(DATA)[1]){
  if(is.na(DATA$early_reaction[i]) & is.na(DATA$late_reaction[i])) {
    DATA$only_early[i] <- NA
  }
  if(is.na(DATA$early_reaction[i]) | is.na(DATA$late_reaction[i])) {
    DATA$only_early[i] <- NA
  }
  if( (!is.na(DATA$early_reaction[i]) & !is.na(DATA$late_reaction[i])) & DATA$early_reaction[i]=="yes" & DATA$late_reaction[i]=="no"){
    DATA$only_early[i] <- "yes"
  }
  if( (!is.na(DATA$early_reaction[i]) & !is.na(DATA$late_reaction[i])) & (DATA$early_reaction[i]!="yes" | DATA$late_reaction[i]!="no")){
    DATA$only_early[i] <- "no"
  }
}

DATA$only_late<-NULL
for(i in 1:dim(DATA)[1]){
  if(is.na(DATA$early_reaction[i]) | is.na(DATA$late_reaction[i])) {
    DATA$only_late[i] <- NA
  }
  
  if( (!is.na(DATA$early_reaction[i]) & !is.na(DATA$late_reaction[i])) & DATA$early_reaction[i]=="no" & DATA$late_reaction[i]=="yes"){
    DATA$only_late[i] <- "yes"
  }
  if( (!is.na(DATA$early_reaction[i]) & !is.na(DATA$late_reaction[i])) & (DATA$early_reaction[i]!="no" | DATA$late_reaction[i]!="yes")){
    DATA$only_late[i] <- "no"
  }
}

DATA$early_late<-NULL
for(i in 1:dim(DATA)[1]){
  if(is.na(DATA$early_reaction[i]) | is.na(DATA$late_reaction[i])) {
    DATA$early_late[i] <- NA
  }
  
  if( (!is.na(DATA$early_reaction[i]) & !is.na(DATA$late_reaction[i])) & DATA$early_reaction[i]=="yes" & DATA$late_reaction[i]=="yes"){
    DATA$early_late[i] <- "yes"
  }
  if( (!is.na(DATA$early_reaction[i]) & !is.na(DATA$late_reaction[i])) & (DATA$early_reaction[i]=="no" | DATA$late_reaction[i]=="no")){
    DATA$early_late[i] <- "no"
  }
}
DATA$pre_eosino.61<-NULL
for(i in 1:dim(DATA)[1]){
  if(is.na(DATA$eosino_pre_sic.3[i]) | is.na(DATA$neutro_pre_sic.61[i])) {
    DATA$pre_eosino.61[i] <- NA
  }
  
  if( (!is.na(DATA$eosino_pre_sic.3[i]) & !is.na(DATA$neutro_pre_sic.61[i])) & DATA$eosino_pre_sic.3[i]=="yes" & DATA$neutro_pre_sic.61[i]=="no"){
    DATA$pre_eosino.61[i] <- "yes"
  }
  if( (!is.na(DATA$eosino_pre_sic.3[i]) & !is.na(DATA$neutro_pre_sic.61[i])) & (DATA$eosino_pre_sic.3[i]!="yes" | DATA$neutro_pre_sic.61[i]!="no")){
    DATA$pre_eosino.61[i] <- "no"
  }
}

DATA$pre.eosino.76<-NULL
for(i in 1:dim(DATA)[1]){
  if(is.na(DATA$eosino_pre_sic.3[i]) | is.na(DATA$neutro_pre_sic.76[i])) {
    DATA$pre.eosino.76[i] <- NA
  }
  
  if( (!is.na(DATA$eosino_pre_sic.3[i]) & !is.na(DATA$neutro_pre_sic.76[i])) & DATA$eosino_pre_sic.3[i]=="yes" & DATA$neutro_pre_sic.76[i]=="no"){
    DATA$pre.eosino.76[i] <- "yes"
  }
  if( (!is.na(DATA$eosino_pre_sic.3[i]) & !is.na(DATA$neutro_pre_sic.76[i])) & (DATA$eosino_pre_sic.3[i]!="yes" | DATA$neutro_pre_sic.76[i]!="no")){
    DATA$pre.eosino.76[i] <- "no"
  }
}

DATA$pre_neutro.76<-NULL
for(i in 1:dim(DATA)[1]){
  if(is.na(DATA$neutro_pre_sic.76[i])|is.na(DATA$eosino_pre_sic.3[i])){
    DATA$pre_neutro.76[i]<-NA
  }
  if((!is.na(DATA$neutro_pre_sic.76[i]) & !is.na(DATA$eosino_pre_sic.3[i])) & (DATA$neutro_pre_sic.76[i]=="yes" & DATA$eosino_pre_sic.3[i]=="no")){
    DATA$pre_neutro.76[i]<-"yes"
  }
  if((!is.na(DATA$neutro_pre_sic.76[i]) & !is.na(DATA$eosino_pre_sic.3[i])) & (DATA$neutro_pre_sic.76[i]!="yes" & DATA$eosino_pre_sic.3[i]!="no")){
    DATA$pre_neutro.76[i]<-"no"
  }
}

DATA$pre_mixte.76<-NULL
for(i in 1:dim(DATA)[1]){
  if(is.na(DATA$eosino_pre_sic.3[i]) | is.na(DATA$neutro_pre_sic.76[i])) {
    DATA$pre_mixed.76[i] <- NA
  }
  
  if( (!is.na(DATA$eosino_pre_sic.3[i]) & !is.na(DATA$neutro_pre_sic.76[i])) & DATA$eosino_pre_sic.3[i]=="yes" & DATA$neutro_pre_sic.76[i]=="yes"){
    DATA$pre_mixed.76[i] <- "yes"
  }
  if( (!is.na(DATA$eosino_pre_sic.3[i]) & !is.na(DATA$neutro_pre_sic.76[i])) & (DATA$eosino_pre_sic.3[i]!="yes" | DATA$neutro_pre_sic.76[i]!="yes")){
    DATA$pre_mixed.76[i] <- "no"
  }
}

DATA$pre_pauci.76<-NULL
for(i in 1:dim(DATA)[1]){
  if(is.na(DATA$eosino_pre_sic.3[i]) | is.na(DATA$neutro_pre_sic.76[i])) {
    DATA$pre_pauci.76[i] <- NA
  }
  
  if( (!is.na(DATA$eosino_pre_sic.3[i]) & !is.na(DATA$neutro_pre_sic.76[i])) & DATA$eosino_pre_sic.3[i]=="no" & DATA$neutro_pre_sic.76[i]=="no"){
    DATA$pre_pauci.76[i] <- "yes"
  }
  if( (!is.na(DATA$eosino_pre_sic.3[i]) & !is.na(DATA$neutro_pre_sic.76[i])) & (DATA$eosino_pre_sic.3[i]!="no" | DATA$neutro_pre_sic.76[i]!="no")){
    DATA$pre_pauci.76[i] <- "no"
  }
}
DATA$rhinitis_sx_sic<-tolower(DATA$rhinitis_sx_sic)

DATA$t235 <- ifelse(is.na(DATA$feno_pre_sic) & is.na(DATA$blood_eosino) & is.na(DATA$eosino_pre_sic), NA, ifelse(DATA$feno_pre_sic >= 35 | DATA$blood_eosino >= 300 | DATA$eosino_pre_sic >=3, 1, ifelse(DATA$feno_pre_sic < 35 & DATA$blood_eosino < 300 & DATA$eosino_pre_sic < 3, 0, NA)))


DATA$ics_w_gina<-tolower(DATA$ics_w_gina)

###création nouvelle variable t250: critère T2 pour eo sang 400, feno 50 et eo crachat 3

DATA$t250 <- ifelse(is.na(DATA$feno_pre_sic) & is.na(DATA$blood_eosino) & is.na(DATA$eosino_pre_sic), NA, ifelse(DATA$feno_pre_sic >= 50 | DATA$blood_eosino >= 400 | DATA$eosino_pre_sic >=3, 1, ifelse(DATA$feno_pre_sic < 50 & DATA$blood_eosino < 400 & DATA$eosino_pre_sic < 3, 0, NA)))


DATA$rhinitis_onset<-ifelse(test = DATA$onset_of_rhinitis_w=="before","before","not before")

DATA$nsbh.res<-factor(DATA$nsbh.res,c("negative","mild","moderate to severe"))
DATA$severity_asthma_gina_sic<-factor(DATA$severity_asthma_gina_sic,c("no treatment","mild","moderate","severe"))

DATA$blood_eosino_400<-ifelse(DATA$blood_eosino>=400,"yes","no")
table(DATA$blood_eosino_400)

DATA$t2p <- ifelse(DATA$eosino_pre_sic.3 == 'yes', 1, 
                      ifelse(DATA$eosino_pre_sic.3 == 'no', 0, 
                      ifelse(DATA$blood_eosino_400 == 'yes' | DATA$feno_pre_sic.50 == 'yes', 1,
                      ifelse(DATA$blood_eosino_400 == 'no' & DATA$feno_pre_sic.50 == 'no', 0, NA))))

table(DATA$t2p)


DATA2<-DATA[!is.na(DATA$t235),]

DATA3<-DATA[!is.na(DATA$t250),]

DATA4<-DATA[!is.na(DATA$eosino_pre_sic.3),]

write.table(x = DATA, file = "DATAclean2.csv", sep = ";", row.names = FALSE)

write.table(x = DATA2, file = "DATAshort.csv", sep = ";", row.names = FALSE)

write.table(x = DATA3, file = "DATAshort50.csv", sep = ";", row.names = FALSE)

write.table(x = DATA4, file = "DATAshort.3.csv", sep = ";", row.names = FALSE)

```

## Description des données manquantes
```{r,(echo=FALSE)}
(sapply(DATA,function(x) sum(is.na(x))))*100/1518


missmap(DATA, main = "Missing values vs observed")

```

```{r}
(sapply(DATA2,function(x) sum(is.na(x))))*100/634


missmap(DATA2, main = "Missing values vs observed")
```

###analyse descriptive sur l'ensemble de la population sur la répartition en catégorie d'agent

```{r}
#prick
by(DATA$prick_test,DATA$agent_category,summary)

#Ige Spécifique
by(DATA$specific_ige,DATA$agent_category,summary)

```

